---
- name: SSH to Cisco NX-OS device
  hosts: nexus
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Show version
      cisco.nxos.nxos_command:
        commands: show version
      register: version_output

    - name: Print version output
      debug:
        var: version_output.stdout_lines