---
- name: Backup Nexus device configuration
  hosts: nexus
  tasks:
    - name: Backup Nexus device
      nxos_config:
        backup: true  
        backup_options:
          filename: "nexus_backup_{{ inventory_hostname }}.txt"
          dir_path: "{{ backup_dir }}"
          #dir_path: ./Backups
      register: backup_result

    - name: Display backup result
      debug:
        var: backup_result
    
    - name: Copy backup to backup server
      copy:
        src: "{{ backup_dir }}/nexus_backup_{{ inventory_hostname }}.txt"
        dest: "C:\\Users\\kamle\\OneDrive\\Documents\\Ansible\\Nexus-Ansible\\Backups\\nexus_backup_{{ inventory_hostname }}.txt"
      delegate_to: backup-server
      when: backup_result.changed
      