---
- name: Backup CISCO Router configuration to Ansible AWX and then to a remote server
  hosts: switch
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Backup ios device
      ios_config:
        backup: true
        backup_options:
          filename: "sw_backup_{{ inventory_hostname }}.txt"
          dir_path: /tmp
      register: backup_result

    - name: Ensure remote backup directory exists
      file:
        path: /home/kam/Documents/NexusBackup
        state: directory
        mode: '0755'
      delegate_to: backup-server

    - name: Copy backup to remote server
      copy:
        src: "/tmp/sw_backup_{{ inventory_hostname }}.txt"
        dest: "/home/kam/Documents/NexusBackup/sw_backup_{{ inventory_hostname }}.txt"
      delegate_to: backup-server
      when: backup_result.changed

    - name: Show backup file path
      debug:
        msg: "Backup saved to /tmp/sw_backup_{{ inventory_hostname }}.txt and copied to backup-server:/home/kam/Documents/NexusBackup/sw_backup_{{ inventory_hostname }}.txt"